//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassEffect3.SaveEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassEffect3.SaveEdit.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string Editor_BasicTable_Character_Class {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Character_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender*.
        /// </summary>
        internal static string Editor_BasicTable_Character_Gender {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Character_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string Editor_BasicTable_Character_Label {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Character_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Editor_BasicTable_Character_Level {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Character_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Editor_BasicTable_Character_Name {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Character_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notoriety.
        /// </summary>
        internal static string Editor_BasicTable_Character_Notoriety {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Character_Notoriety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        internal static string Editor_BasicTable_Character_Origin {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Character_Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talent Points.
        /// </summary>
        internal static string Editor_BasicTable_Character_TalentPoints {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Character_TalentPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current XP.
        /// </summary>
        internal static string Editor_BasicTable_Character_XP {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Character_XP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:.
        /// </summary>
        internal static string Editor_BasicTable_ItemLabelFormat {
            get {
                return ResourceManager.GetString("Editor_BasicTable_ItemLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        internal static string Editor_BasicTable_Reputation_Label {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Reputation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon Points.
        /// </summary>
        internal static string Editor_BasicTable_Reputation_ParagonPoints {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Reputation_ParagonPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renegade Points.
        /// </summary>
        internal static string Editor_BasicTable_Reputation_RenegadePoints {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Reputation_RenegadePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        internal static string Editor_BasicTable_Reputation_Reputation {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Reputation_Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation Points.
        /// </summary>
        internal static string Editor_BasicTable_Reputation_ReputationPoints {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Reputation_ReputationPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Squad.
        /// </summary>
        internal static string Editor_BasicTable_Reset_Label {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Reset_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Editor_BasicTable_Resources_Credits {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Resources_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Medi-gel.
        /// </summary>
        internal static string Editor_BasicTable_Resources_ExtraMedigel {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Resources_ExtraMedigel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenades.
        /// </summary>
        internal static string Editor_BasicTable_Resources_Grenades {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Resources_Grenades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string Editor_BasicTable_Resources_Label {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Resources_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medi-gel.
        /// </summary>
        internal static string Editor_BasicTable_Resources_Medigel {
            get {
                return ResourceManager.GetString("Editor_BasicTable_Resources_Medigel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Build revision {0} @ {1}).
        /// </summary>
        internal static string Editor_BuildRevision {
            get {
                return ResourceManager.GetString("Editor_BuildRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot open Xbox 360 CON files with the save editor..
        /// </summary>
        internal static string Editor_CannotLoadXbox360CONFile {
            get {
                return ResourceManager.GetString("Editor_CannotLoadXbox360CONFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Name.
        /// </summary>
        internal static string Editor_ColorName {
            get {
                return ResourceManager.GetString("Editor_ColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool ID {0} already added.
        /// </summary>
        internal static string Editor_DuplicatePlotBool {
            get {
                return ResourceManager.GetString("Editor_DuplicatePlotBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int ID {0} already added.
        /// </summary>
        internal static string Editor_DuplicatePlotInt {
            get {
                return ResourceManager.GetString("Editor_DuplicatePlotInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse id..
        /// </summary>
        internal static string Editor_FailedToParseId {
            get {
                return ResourceManager.GetString("Editor_FailedToParseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse value..
        /// </summary>
        internal static string Editor_FailedToParseValue {
            get {
                return ResourceManager.GetString("Editor_FailedToParseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That file does not appear to be an exported head morph..
        /// </summary>
        internal static string Editor_HeadMorphInvalid {
            get {
                return ResourceManager.GetString("Editor_HeadMorphInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While you can import head morph data created by Mass Effect 2, it is unlikely to work properly.
        ///
        ///Are you sure you want to import a legacy head morph?.
        /// </summary>
        internal static string Editor_HeadMorphLegacy {
            get {
                return ResourceManager.GetString("Editor_HeadMorphLegacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The head morph you are importing has a different version ({0}) than your current save file ({1}).
        ///
        ///Import anyway?.
        /// </summary>
        internal static string Editor_HeadMorphVersionMaybeIncompatible {
            get {
                return ResourceManager.GetString("Editor_HeadMorphVersionMaybeIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported head morph export version..
        /// </summary>
        internal static string Editor_HeadMorphVersionUnsupported {
            get {
                return ResourceManager.GetString("Editor_HeadMorphVersionUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active save..
        /// </summary>
        internal static string Editor_NoActiveSave {
            get {
                return ResourceManager.GetString("Editor_NoActiveSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This save does not have a non-default head morph..
        /// </summary>
        internal static string Editor_NoHeadMorph {
            get {
                return ResourceManager.GetString("Editor_NoHeadMorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading {0}!
        ///
        ///{1}.
        /// </summary>
        internal static string Editor_PlotCategoryLoadError {
            get {
                return ResourceManager.GetString("Editor_PlotCategoryLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string Editor_PlotEditor_BoolsLabel {
            get {
                return ResourceManager.GetString("Editor_PlotEditor_BoolsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floats.
        /// </summary>
        internal static string Editor_PlotEditor_FloatsLabel {
            get {
                return ResourceManager.GetString("Editor_PlotEditor_FloatsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integers.
        /// </summary>
        internal static string Editor_PlotEditor_IntsLabel {
            get {
                return ResourceManager.GetString("Editor_PlotEditor_IntsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string Editor_PlotEditor_NoteLabel {
            get {
                return ResourceManager.GetString("Editor_PlotEditor_NoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Editor_PlotEditor_ValueLabelFormat {
            get {
                return ResourceManager.GetString("Editor_PlotEditor_ValueLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool {0} is set to {1}.
        /// </summary>
        internal static string Editor_PlotManualLogBoolGet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogBoolGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bool {0} set to {1} (was {2}).
        /// </summary>
        internal static string Editor_PlotManualLogBoolSet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogBoolSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float {0} is set to {1}.
        /// </summary>
        internal static string Editor_PlotManualLogFloatGet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogFloatGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to float {0} set to {1} (was {2}).
        /// </summary>
        internal static string Editor_PlotManualLogFloatSet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogFloatSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int {0} is set to {1}.
        /// </summary>
        internal static string Editor_PlotManualLogIntGet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogIntGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to int {0} set to {1} (was {2}).
        /// </summary>
        internal static string Editor_PlotManualLogIntSet {
            get {
                return ResourceManager.GetString("Editor_PlotManualLogIntSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is set to {1}.
        /// </summary>
        internal static string Editor_PlotManualPlayerVarLogGet {
            get {
                return ResourceManager.GetString("Editor_PlotManualPlayerVarLogGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} set to {1} (was {2}).
        /// </summary>
        internal static string Editor_PlotManualPlayerVarLogSet {
            get {
                return ResourceManager.GetString("Editor_PlotManualPlayerVarLogSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The save file you have tried to load is too old for the Save Editor. You have probably tried to load a Mass Effect 2 save file..
        /// </summary>
        internal static string Editor_SaveFileTooOld {
            get {
                return ResourceManager.GetString("Editor_SaveFileTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an exception trying to read the save file.
        ///Please report this message to Rick (ctrl+C to copy this dialog) and include a copy of the save file you tried to load.
        ///
        ///{0}.
        /// </summary>
        internal static string Editor_SaveReadException {
            get {
                return ResourceManager.GetString("Editor_SaveReadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should never happen..
        /// </summary>
        internal static string Editor_ThisShouldNeverHappen {
            get {
                return ResourceManager.GetString("Editor_ThisShouldNeverHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adept.
        /// </summary>
        internal static string PlayerClass_Adept {
            get {
                return ResourceManager.GetString("PlayerClass_Adept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adept (out of combat).
        /// </summary>
        internal static string PlayerClass_AdeptNonCombat {
            get {
                return ResourceManager.GetString("PlayerClass_AdeptNonCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer.
        /// </summary>
        internal static string PlayerClass_Engineer {
            get {
                return ResourceManager.GetString("PlayerClass_Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engineer (out of combat).
        /// </summary>
        internal static string PlayerClass_EngineerNonCombat {
            get {
                return ResourceManager.GetString("PlayerClass_EngineerNonCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infiltrator.
        /// </summary>
        internal static string PlayerClass_Infiltrator {
            get {
                return ResourceManager.GetString("PlayerClass_Infiltrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infiltrator (out of combat).
        /// </summary>
        internal static string PlayerClass_InfiltratorNonCombat {
            get {
                return ResourceManager.GetString("PlayerClass_InfiltratorNonCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel.
        /// </summary>
        internal static string PlayerClass_Sentinel {
            get {
                return ResourceManager.GetString("PlayerClass_Sentinel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentinel (out of combat).
        /// </summary>
        internal static string PlayerClass_SentinelNonCombat {
            get {
                return ResourceManager.GetString("PlayerClass_SentinelNonCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier.
        /// </summary>
        internal static string PlayerClass_Soldier {
            get {
                return ResourceManager.GetString("PlayerClass_Soldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldier (out of combat).
        /// </summary>
        internal static string PlayerClass_SoldierNonCombat {
            get {
                return ResourceManager.GetString("PlayerClass_SoldierNonCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanguard.
        /// </summary>
        internal static string PlayerClass_Vanguard {
            get {
                return ResourceManager.GetString("PlayerClass_Vanguard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanguard (out of combat).
        /// </summary>
        internal static string PlayerClass_VanguardNonCombat {
            get {
                return ResourceManager.GetString("PlayerClass_VanguardNonCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string PlayerGender_Female {
            get {
                return ResourceManager.GetString("PlayerGender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string PlayerGender_Male {
            get {
                return ResourceManager.GetString("PlayerGender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PlayerNotoriety_None {
            get {
                return ResourceManager.GetString("PlayerNotoriety_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruthless.
        /// </summary>
        internal static string PlayerNotoriety_Ruthless {
            get {
                return ResourceManager.GetString("PlayerNotoriety_Ruthless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sole Survivor.
        /// </summary>
        internal static string PlayerNotoriety_Survivor {
            get {
                return ResourceManager.GetString("PlayerNotoriety_Survivor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to War Hero.
        /// </summary>
        internal static string PlayerNotoriety_Warhero {
            get {
                return ResourceManager.GetString("PlayerNotoriety_Warhero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colonist.
        /// </summary>
        internal static string PlayerOrigin_Colony {
            get {
                return ResourceManager.GetString("PlayerOrigin_Colony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earthborn.
        /// </summary>
        internal static string PlayerOrigin_Earthborn {
            get {
                return ResourceManager.GetString("PlayerOrigin_Earthborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PlayerOrigin_None {
            get {
                return ResourceManager.GetString("PlayerOrigin_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacer.
        /// </summary>
        internal static string PlayerOrigin_Spacer {
            get {
                return ResourceManager.GetString("PlayerOrigin_Spacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this career?.
        /// </summary>
        internal static string SavePicker_DeleteCareerConfirmation {
            get {
                return ResourceManager.GetString("SavePicker_DeleteCareerConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error removing the directory:
        ///
        ///{0}.
        /// </summary>
        internal static string SavePicker_DeleteCareerIOException {
            get {
                return ResourceManager.GetString("SavePicker_DeleteCareerIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this save?.
        /// </summary>
        internal static string SavePicker_DeleteSaveConfirmation {
            get {
                return ResourceManager.GetString("SavePicker_DeleteSaveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error removing the file:
        ///
        ///{0}.
        /// </summary>
        internal static string SavePicker_DeleteSaveIOException {
            get {
                return ResourceManager.GetString("SavePicker_DeleteSaveIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (new career).
        /// </summary>
        internal static string SavePicker_NewCareerLabel {
            get {
                return ResourceManager.GetString("SavePicker_NewCareerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (new save).
        /// </summary>
        internal static string SavePicker_NewSaveLabel {
            get {
                return ResourceManager.GetString("SavePicker_NewSaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to overwrite this save file?.
        /// </summary>
        internal static string SavePicker_SaveOverwriteConfirmation {
            get {
                return ResourceManager.GetString("SavePicker_SaveOverwriteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
