var _annotations_8cs =
[
    [ "LegendaryExplorerCore.Gammtek.CanBeNullAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_can_be_null_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.NotNullAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_not_null_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.ItemNotNullAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_item_not_null_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.ItemCanBeNullAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_item_can_be_null_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.StringFormatMethodAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_string_format_method_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_string_format_method_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.ValueProviderAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_value_provider_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_value_provider_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.InvokerParameterNameAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_invoker_parameter_name_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.NotifyPropertyChangedInvocatorAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_notify_property_changed_invocator_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_notify_property_changed_invocator_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.ContractAnnotationAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_contract_annotation_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_contract_annotation_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.LocalizationRequiredAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_localization_required_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_localization_required_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.CannotApplyEqualityOperatorAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_cannot_apply_equality_operator_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.BaseTypeRequiredAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_base_type_required_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_base_type_required_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.UsedImplicitlyAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_used_implicitly_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_used_implicitly_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.MeansImplicitUseAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_means_implicit_use_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_means_implicit_use_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.PublicAPIAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_public_a_p_i_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_public_a_p_i_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.InstantHandleAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_instant_handle_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.PureAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_pure_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.MustUseReturnValueAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_must_use_return_value_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_must_use_return_value_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.ProvidesContextAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_provides_context_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.PathReferenceAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_path_reference_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_path_reference_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.SourceTemplateAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_source_template_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.MacroAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_macro_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_macro_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcAreaMasterLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_master_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_master_location_format_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcAreaPartialViewLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_partial_view_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_partial_view_location_format_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcAreaViewLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_view_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_view_location_format_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcMasterLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_master_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_master_location_format_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcPartialViewLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_partial_view_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_partial_view_location_format_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcViewLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_view_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_view_location_format_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcActionAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_action_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_action_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcAreaAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcControllerAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_controller_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_controller_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcMasterAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_master_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcModelTypeAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_model_type_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcPartialViewAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_partial_view_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcSuppressViewErrorAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_suppress_view_error_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcDisplayTemplateAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_display_template_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcEditorTemplateAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_editor_template_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcTemplateAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_template_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcViewAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_view_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcViewComponentAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_view_component_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcViewComponentViewAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_view_component_view_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMvcActionSelectorAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_action_selector_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.HtmlElementAttributesAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_html_element_attributes_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_html_element_attributes_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.HtmlAttributeValueAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_html_attribute_value_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_html_attribute_value_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.RazorSectionAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_section_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.CollectionAccessAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_collection_access_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_collection_access_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AssertionMethodAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_assertion_method_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AssertionConditionAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_assertion_condition_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_assertion_condition_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.TerminatesProgramAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_terminates_program_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.LinqTunnelAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_linq_tunnel_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.NoEnumerationAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_no_enumeration_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.RegexPatternAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_regex_pattern_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.XamlItemsControlAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_xaml_items_control_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.XamlItemBindingOfItemsControlAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_xaml_item_binding_of_items_control_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspChildControlTypeAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_child_control_type_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_child_control_type_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspDataFieldAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_data_field_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspDataFieldsAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_data_fields_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspMethodPropertyAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_method_property_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.AspRequiredAttributeAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_required_attribute_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_required_attribute_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.AspTypePropertyAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_type_property_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_type_property_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.RazorImportNamespaceAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_import_namespace_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_import_namespace_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.RazorInjectionAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_injection_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_injection_attribute" ],
    [ "LegendaryExplorerCore.Gammtek.RazorHelperCommonAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_helper_common_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.RazorLayoutAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_layout_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.RazorWriteLiteralMethodAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_write_literal_method_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.RazorWriteMethodAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_write_method_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.RazorWriteMethodParameterAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_write_method_parameter_attribute.html", null ],
    [ "LegendaryExplorerCore.Gammtek.NoReorder", "class_legendary_explorer_core_1_1_gammtek_1_1_no_reorder.html", null ],
    [ "ImplicitUseKindFlags", "_annotations_8cs.html#a257e2f7d4427d48f350d0b1740276a3d", [
      [ "Default", "_annotations_8cs.html#a257e2f7d4427d48f350d0b1740276a3da7a1920d61156abc05a60135aefe8bc67", null ],
      [ "Access", "_annotations_8cs.html#a257e2f7d4427d48f350d0b1740276a3dabf733d8a933c1601697f364223fc7ecb", null ],
      [ "Assign", "_annotations_8cs.html#a257e2f7d4427d48f350d0b1740276a3da185b7133db22230701a857c059360cc2", null ],
      [ "InstantiatedWithFixedConstructorSignature", "_annotations_8cs.html#a257e2f7d4427d48f350d0b1740276a3da88199ed5f1baf0dc6ed80a0db9336403", null ],
      [ "InstantiatedNoFixedConstructorSignature", "_annotations_8cs.html#a257e2f7d4427d48f350d0b1740276a3da4ea3601c5369a85043a3d88bbe23d4f6", null ]
    ] ],
    [ "ImplicitUseTargetFlags", "_annotations_8cs.html#abdb33e0d50e0ed925c43c19bf23e3aec", [
      [ "Default", "_annotations_8cs.html#abdb33e0d50e0ed925c43c19bf23e3aeca7a1920d61156abc05a60135aefe8bc67", null ],
      [ "Itself", "_annotations_8cs.html#abdb33e0d50e0ed925c43c19bf23e3aecad24a614afd61a4a9097269b8a7225209", null ],
      [ "Members", "_annotations_8cs.html#abdb33e0d50e0ed925c43c19bf23e3aecaef53538ae41a651c7f72ab6cb1135d8c", null ],
      [ "WithMembers", "_annotations_8cs.html#abdb33e0d50e0ed925c43c19bf23e3aeca5583bb135f4d32715af96327c369e623", null ]
    ] ],
    [ "CollectionAccessType", "_annotations_8cs.html#a86220dd30688e36c225063187ae783d3", [
      [ "None", "_annotations_8cs.html#a86220dd30688e36c225063187ae783d3a6adf97f83acf6453d4a6a4b1070f3754", null ],
      [ "Read", "_annotations_8cs.html#a86220dd30688e36c225063187ae783d3a7a1a5f3e79fdc91edf2f5ead9d66abb4", null ],
      [ "ModifyExistingContent", "_annotations_8cs.html#a86220dd30688e36c225063187ae783d3aabf21948b8bdc6b576703a901052dc09", null ],
      [ "UpdatedContent", "_annotations_8cs.html#a86220dd30688e36c225063187ae783d3a424cc5446574f01d7f484e158b23d001", null ]
    ] ],
    [ "AssertionConditionType", "_annotations_8cs.html#a9433cc61cc685d9cf964d6871ac7e091", [
      [ "IS_TRUE", "_annotations_8cs.html#a9433cc61cc685d9cf964d6871ac7e091a23cd5ba5c6eed3d82ba0c6c0526df429", null ],
      [ "IS_FALSE", "_annotations_8cs.html#a9433cc61cc685d9cf964d6871ac7e091adeab83d56dee7ab418359a59b4ff2eb0", null ],
      [ "IS_NULL", "_annotations_8cs.html#a9433cc61cc685d9cf964d6871ac7e091adbd9c38e0339e6c34bd48cafc59be388", null ],
      [ "IS_NOT_NULL", "_annotations_8cs.html#a9433cc61cc685d9cf964d6871ac7e091a05dd132ba23ff57c0ca5ec4100c31fdc", null ]
    ] ]
];