var _default_string_matcher_8cs =
[
    [ "LegendaryExplorerCore.Gammtek.Text.StringMatching.DefaultStringMatcher", "class_legendary_explorer_core_1_1_gammtek_1_1_text_1_1_string_matching_1_1_default_string_matcher.html", "class_legendary_explorer_core_1_1_gammtek_1_1_text_1_1_string_matching_1_1_default_string_matcher" ]
];