var _default_properties_block_8cs =
[
    [ "LegendaryExplorerCore.UnrealScript.Language.Tree.DefaultPropertiesBlock", "class_legendary_explorer_core_1_1_unreal_script_1_1_language_1_1_tree_1_1_default_properties_block.html", "class_legendary_explorer_core_1_1_unreal_script_1_1_language_1_1_tree_1_1_default_properties_block" ]
];