var _entry_importer_8cs =
[
    [ "LegendaryExplorerCore.Packages.CloningImportingAndRelinking.PortingOptions", "class_legendary_explorer_core_1_1_packages_1_1_cloning_importing_and_relinking_1_1_porting_options.html", "class_legendary_explorer_core_1_1_packages_1_1_cloning_importing_and_relinking_1_1_porting_options" ],
    [ "LegendaryExplorerCore.Packages.CloningImportingAndRelinking.EntryImporter", "class_legendary_explorer_core_1_1_packages_1_1_cloning_importing_and_relinking_1_1_entry_importer.html", "class_legendary_explorer_core_1_1_packages_1_1_cloning_importing_and_relinking_1_1_entry_importer" ]
];