var _object_instance_d_b_8cs =
[
    [ "LegendaryExplorerCore.Packages.CloningImportingAndRelinking.ObjectInstanceDB", "class_legendary_explorer_core_1_1_packages_1_1_cloning_importing_and_relinking_1_1_object_instance_d_b.html", "class_legendary_explorer_core_1_1_packages_1_1_cloning_importing_and_relinking_1_1_object_instance_d_b" ],
    [ "LegendaryExplorerCore.Packages.CloningImportingAndRelinking.ObjectInstanceInfo", "class_legendary_explorer_core_1_1_packages_1_1_cloning_importing_and_relinking_1_1_object_instance_info.html", "class_legendary_explorer_core_1_1_packages_1_1_cloning_importing_and_relinking_1_1_object_instance_info" ]
];