var _serialized_plot_database_8cs =
[
    [ "LegendaryExplorerCore.PlotDatabase.Serialization.SerializedPlotDatabase", "class_legendary_explorer_core_1_1_plot_database_1_1_serialization_1_1_serialized_plot_database.html", "class_legendary_explorer_core_1_1_plot_database_1_1_serialization_1_1_serialized_plot_database" ]
];