var _verbose_format_info_base_8cs =
[
    [ "LegendaryExplorerCore.Gammtek.Text.Formatting.VerboseFormatInfoBase", "class_legendary_explorer_core_1_1_gammtek_1_1_text_1_1_formatting_1_1_verbose_format_info_base.html", "class_legendary_explorer_core_1_1_gammtek_1_1_text_1_1_formatting_1_1_verbose_format_info_base" ]
];