var namespace_legendary_explorer_core_1_1_plot_database_1_1_serialization =
[
    [ "SerializedModPlotDatabase", "class_legendary_explorer_core_1_1_plot_database_1_1_serialization_1_1_serialized_mod_plot_database.html", "class_legendary_explorer_core_1_1_plot_database_1_1_serialization_1_1_serialized_mod_plot_database" ],
    [ "SerializedPlotDatabase", "class_legendary_explorer_core_1_1_plot_database_1_1_serialization_1_1_serialized_plot_database.html", "class_legendary_explorer_core_1_1_plot_database_1_1_serialization_1_1_serialized_plot_database" ]
];