var namespace_legendary_explorer_core_1_1_packages =
[
    [ "CloningImportingAndRelinking", "namespace_legendary_explorer_core_1_1_packages_1_1_cloning_importing_and_relinking.html", "namespace_legendary_explorer_core_1_1_packages_1_1_cloning_importing_and_relinking" ],
    [ "ClassInfo", "class_legendary_explorer_core_1_1_packages_1_1_class_info.html", "class_legendary_explorer_core_1_1_packages_1_1_class_info" ],
    [ "CompressionHelper", "class_legendary_explorer_core_1_1_packages_1_1_compression_helper.html", "class_legendary_explorer_core_1_1_packages_1_1_compression_helper" ],
    [ "DisposableCollection", "class_legendary_explorer_core_1_1_packages_1_1_disposable_collection.html", "class_legendary_explorer_core_1_1_packages_1_1_disposable_collection" ],
    [ "EntryTree", "class_legendary_explorer_core_1_1_packages_1_1_entry_tree.html", "class_legendary_explorer_core_1_1_packages_1_1_entry_tree" ],
    [ "ExportCreator", "class_legendary_explorer_core_1_1_packages_1_1_export_creator.html", "class_legendary_explorer_core_1_1_packages_1_1_export_creator" ],
    [ "ExportEntry", "class_legendary_explorer_core_1_1_packages_1_1_export_entry.html", "class_legendary_explorer_core_1_1_packages_1_1_export_entry" ],
    [ "ExportEntryExtensions", "class_legendary_explorer_core_1_1_packages_1_1_export_entry_extensions.html", "class_legendary_explorer_core_1_1_packages_1_1_export_entry_extensions" ],
    [ "IEntry", "interface_legendary_explorer_core_1_1_packages_1_1_i_entry.html", "interface_legendary_explorer_core_1_1_packages_1_1_i_entry" ],
    [ "IEntryExtensions", "class_legendary_explorer_core_1_1_packages_1_1_i_entry_extensions.html", "class_legendary_explorer_core_1_1_packages_1_1_i_entry_extensions" ],
    [ "IMEPackage", "interface_legendary_explorer_core_1_1_packages_1_1_i_m_e_package.html", "interface_legendary_explorer_core_1_1_packages_1_1_i_m_e_package" ],
    [ "ImportEntry", "class_legendary_explorer_core_1_1_packages_1_1_import_entry.html", "class_legendary_explorer_core_1_1_packages_1_1_import_entry" ],
    [ "IPackageUser", "interface_legendary_explorer_core_1_1_packages_1_1_i_package_user.html", "interface_legendary_explorer_core_1_1_packages_1_1_i_package_user" ],
    [ "IWeakPackageUser", "interface_legendary_explorer_core_1_1_packages_1_1_i_weak_package_user.html", "interface_legendary_explorer_core_1_1_packages_1_1_i_weak_package_user" ],
    [ "LECLData", "class_legendary_explorer_core_1_1_packages_1_1_l_e_c_l_data.html", "class_legendary_explorer_core_1_1_packages_1_1_l_e_c_l_data" ],
    [ "MEGameExtensions", "class_legendary_explorer_core_1_1_packages_1_1_m_e_game_extensions.html", "class_legendary_explorer_core_1_1_packages_1_1_m_e_game_extensions" ],
    [ "MELocalizationExtensions", "class_legendary_explorer_core_1_1_packages_1_1_m_e_localization_extensions.html", "class_legendary_explorer_core_1_1_packages_1_1_m_e_localization_extensions" ],
    [ "MEPackage", "class_legendary_explorer_core_1_1_packages_1_1_m_e_package.html", "class_legendary_explorer_core_1_1_packages_1_1_m_e_package" ],
    [ "MEPackageExtensions", "class_legendary_explorer_core_1_1_packages_1_1_m_e_package_extensions.html", "class_legendary_explorer_core_1_1_packages_1_1_m_e_package_extensions" ],
    [ "MEPackageHandler", "class_legendary_explorer_core_1_1_packages_1_1_m_e_package_handler.html", "class_legendary_explorer_core_1_1_packages_1_1_m_e_package_handler" ],
    [ "PackageCache", "class_legendary_explorer_core_1_1_packages_1_1_package_cache.html", "class_legendary_explorer_core_1_1_packages_1_1_package_cache" ],
    [ "PackageSaver", "class_legendary_explorer_core_1_1_packages_1_1_package_saver.html", "class_legendary_explorer_core_1_1_packages_1_1_package_saver" ],
    [ "PackageUpdate", "struct_legendary_explorer_core_1_1_packages_1_1_package_update.html", "struct_legendary_explorer_core_1_1_packages_1_1_package_update" ],
    [ "PropertyInfo", "class_legendary_explorer_core_1_1_packages_1_1_property_info.html", "class_legendary_explorer_core_1_1_packages_1_1_property_info" ],
    [ "UDKPackage", "class_legendary_explorer_core_1_1_packages_1_1_u_d_k_package.html", "class_legendary_explorer_core_1_1_packages_1_1_u_d_k_package" ],
    [ "UnrealPackageFile", "class_legendary_explorer_core_1_1_packages_1_1_unreal_package_file.html", "class_legendary_explorer_core_1_1_packages_1_1_unreal_package_file" ],
    [ "ArrayType", "namespace_legendary_explorer_core_1_1_packages.html#a01ab7fe2b35882890ba5f989fefef344", null ],
    [ "MEGame", "namespace_legendary_explorer_core_1_1_packages.html#a386a95aceb8dcc8725a8cb074fd0e6a8", null ],
    [ "MELocalization", "namespace_legendary_explorer_core_1_1_packages.html#aefbc0ecf962a8819f213240cc7553d90", null ],
    [ "PackageChange", "namespace_legendary_explorer_core_1_1_packages.html#a3e0df23952f452387a53678322854238", null ]
];