var namespace_legendary_explorer_core_1_1_gammtek =
[
    [ "Collections", "namespace_legendary_explorer_core_1_1_gammtek_1_1_collections.html", "namespace_legendary_explorer_core_1_1_gammtek_1_1_collections" ],
    [ "ComponentModel", "namespace_legendary_explorer_core_1_1_gammtek_1_1_component_model.html", "namespace_legendary_explorer_core_1_1_gammtek_1_1_component_model" ],
    [ "Data", "namespace_legendary_explorer_core_1_1_gammtek_1_1_data.html", "namespace_legendary_explorer_core_1_1_gammtek_1_1_data" ],
    [ "Dynamic", "namespace_legendary_explorer_core_1_1_gammtek_1_1_dynamic.html", "namespace_legendary_explorer_core_1_1_gammtek_1_1_dynamic" ],
    [ "Extensions", "namespace_legendary_explorer_core_1_1_gammtek_1_1_extensions.html", "namespace_legendary_explorer_core_1_1_gammtek_1_1_extensions" ],
    [ "Helpers", "namespace_legendary_explorer_core_1_1_gammtek_1_1_helpers.html", "namespace_legendary_explorer_core_1_1_gammtek_1_1_helpers" ],
    [ "IO", "namespace_legendary_explorer_core_1_1_gammtek_1_1_i_o.html", "namespace_legendary_explorer_core_1_1_gammtek_1_1_i_o" ],
    [ "Paths", "namespace_legendary_explorer_core_1_1_gammtek_1_1_paths.html", "namespace_legendary_explorer_core_1_1_gammtek_1_1_paths" ],
    [ "Text", "namespace_legendary_explorer_core_1_1_gammtek_1_1_text.html", "namespace_legendary_explorer_core_1_1_gammtek_1_1_text" ],
    [ "Windows", "namespace_legendary_explorer_core_1_1_gammtek_1_1_windows.html", "namespace_legendary_explorer_core_1_1_gammtek_1_1_windows" ],
    [ "Argument", "class_legendary_explorer_core_1_1_gammtek_1_1_argument.html", "class_legendary_explorer_core_1_1_gammtek_1_1_argument" ],
    [ "AspChildControlTypeAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_child_control_type_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_child_control_type_attribute" ],
    [ "AspDataFieldAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_data_field_attribute.html", null ],
    [ "AspDataFieldsAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_data_fields_attribute.html", null ],
    [ "AspMethodPropertyAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_method_property_attribute.html", null ],
    [ "AspMvcActionAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_action_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_action_attribute" ],
    [ "AspMvcActionSelectorAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_action_selector_attribute.html", null ],
    [ "AspMvcAreaAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_attribute" ],
    [ "AspMvcAreaMasterLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_master_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_master_location_format_attribute" ],
    [ "AspMvcAreaPartialViewLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_partial_view_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_partial_view_location_format_attribute" ],
    [ "AspMvcAreaViewLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_view_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_area_view_location_format_attribute" ],
    [ "AspMvcControllerAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_controller_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_controller_attribute" ],
    [ "AspMvcDisplayTemplateAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_display_template_attribute.html", null ],
    [ "AspMvcEditorTemplateAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_editor_template_attribute.html", null ],
    [ "AspMvcMasterAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_master_attribute.html", null ],
    [ "AspMvcMasterLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_master_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_master_location_format_attribute" ],
    [ "AspMvcModelTypeAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_model_type_attribute.html", null ],
    [ "AspMvcPartialViewAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_partial_view_attribute.html", null ],
    [ "AspMvcPartialViewLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_partial_view_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_partial_view_location_format_attribute" ],
    [ "AspMvcSuppressViewErrorAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_suppress_view_error_attribute.html", null ],
    [ "AspMvcTemplateAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_template_attribute.html", null ],
    [ "AspMvcViewAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_view_attribute.html", null ],
    [ "AspMvcViewComponentAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_view_component_attribute.html", null ],
    [ "AspMvcViewComponentViewAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_view_component_view_attribute.html", null ],
    [ "AspMvcViewLocationFormatAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_view_location_format_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_mvc_view_location_format_attribute" ],
    [ "AspRequiredAttributeAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_required_attribute_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_required_attribute_attribute" ],
    [ "AspTypePropertyAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_type_property_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_asp_type_property_attribute" ],
    [ "AssertionConditionAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_assertion_condition_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_assertion_condition_attribute" ],
    [ "AssertionMethodAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_assertion_method_attribute.html", null ],
    [ "BaseTypeRequiredAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_base_type_required_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_base_type_required_attribute" ],
    [ "CanBeNullAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_can_be_null_attribute.html", null ],
    [ "CannotApplyEqualityOperatorAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_cannot_apply_equality_operator_attribute.html", null ],
    [ "CMath", "class_legendary_explorer_core_1_1_gammtek_1_1_c_math.html", "class_legendary_explorer_core_1_1_gammtek_1_1_c_math" ],
    [ "CollectionAccessAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_collection_access_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_collection_access_attribute" ],
    [ "ContractAnnotationAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_contract_annotation_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_contract_annotation_attribute" ],
    [ "Enum", "class_legendary_explorer_core_1_1_gammtek_1_1_enum.html", "class_legendary_explorer_core_1_1_gammtek_1_1_enum" ],
    [ "GammtekUtilities", "class_legendary_explorer_core_1_1_gammtek_1_1_gammtek_utilities.html", "class_legendary_explorer_core_1_1_gammtek_1_1_gammtek_utilities" ],
    [ "HtmlAttributeValueAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_html_attribute_value_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_html_attribute_value_attribute" ],
    [ "HtmlElementAttributesAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_html_element_attributes_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_html_element_attributes_attribute" ],
    [ "IBindableEnum", "interface_legendary_explorer_core_1_1_gammtek_1_1_i_bindable_enum.html", "interface_legendary_explorer_core_1_1_gammtek_1_1_i_bindable_enum" ],
    [ "InstantHandleAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_instant_handle_attribute.html", null ],
    [ "InvokerParameterNameAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_invoker_parameter_name_attribute.html", null ],
    [ "ItemCanBeNullAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_item_can_be_null_attribute.html", null ],
    [ "ItemNotNullAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_item_not_null_attribute.html", null ],
    [ "LinqTunnelAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_linq_tunnel_attribute.html", null ],
    [ "LocalizationRequiredAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_localization_required_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_localization_required_attribute" ],
    [ "MacroAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_macro_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_macro_attribute" ],
    [ "MeansImplicitUseAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_means_implicit_use_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_means_implicit_use_attribute" ],
    [ "MustUseReturnValueAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_must_use_return_value_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_must_use_return_value_attribute" ],
    [ "NoEnumerationAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_no_enumeration_attribute.html", null ],
    [ "NoReorder", "class_legendary_explorer_core_1_1_gammtek_1_1_no_reorder.html", null ],
    [ "NotifyPropertyChangedInvocatorAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_notify_property_changed_invocator_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_notify_property_changed_invocator_attribute" ],
    [ "NotNullAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_not_null_attribute.html", null ],
    [ "PathReferenceAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_path_reference_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_path_reference_attribute" ],
    [ "ProvidesContextAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_provides_context_attribute.html", null ],
    [ "PublicAPIAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_public_a_p_i_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_public_a_p_i_attribute" ],
    [ "PureAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_pure_attribute.html", null ],
    [ "RazorHelperCommonAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_helper_common_attribute.html", null ],
    [ "RazorImportNamespaceAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_import_namespace_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_import_namespace_attribute" ],
    [ "RazorInjectionAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_injection_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_injection_attribute" ],
    [ "RazorLayoutAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_layout_attribute.html", null ],
    [ "RazorSectionAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_section_attribute.html", null ],
    [ "RazorWriteLiteralMethodAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_write_literal_method_attribute.html", null ],
    [ "RazorWriteMethodAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_write_method_attribute.html", null ],
    [ "RazorWriteMethodParameterAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_razor_write_method_parameter_attribute.html", null ],
    [ "RegexPatternAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_regex_pattern_attribute.html", null ],
    [ "SourceTemplateAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_source_template_attribute.html", null ],
    [ "StringFormatMethodAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_string_format_method_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_string_format_method_attribute" ],
    [ "TerminatesProgramAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_terminates_program_attribute.html", null ],
    [ "ThrowHelper", "class_legendary_explorer_core_1_1_gammtek_1_1_throw_helper.html", "class_legendary_explorer_core_1_1_gammtek_1_1_throw_helper" ],
    [ "TypeSwitch", "class_legendary_explorer_core_1_1_gammtek_1_1_type_switch.html", "class_legendary_explorer_core_1_1_gammtek_1_1_type_switch" ],
    [ "UsedImplicitlyAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_used_implicitly_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_used_implicitly_attribute" ],
    [ "ValueProviderAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_value_provider_attribute.html", "class_legendary_explorer_core_1_1_gammtek_1_1_value_provider_attribute" ],
    [ "XamlItemBindingOfItemsControlAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_xaml_item_binding_of_items_control_attribute.html", null ],
    [ "XamlItemsControlAttribute", "class_legendary_explorer_core_1_1_gammtek_1_1_xaml_items_control_attribute.html", null ],
    [ "ImplicitUseKindFlags", "namespace_legendary_explorer_core_1_1_gammtek.html#a257e2f7d4427d48f350d0b1740276a3d", [
      [ "Default", "namespace_legendary_explorer_core_1_1_gammtek.html#a257e2f7d4427d48f350d0b1740276a3da7a1920d61156abc05a60135aefe8bc67", null ],
      [ "Access", "namespace_legendary_explorer_core_1_1_gammtek.html#a257e2f7d4427d48f350d0b1740276a3dabf733d8a933c1601697f364223fc7ecb", null ],
      [ "Assign", "namespace_legendary_explorer_core_1_1_gammtek.html#a257e2f7d4427d48f350d0b1740276a3da185b7133db22230701a857c059360cc2", null ],
      [ "InstantiatedWithFixedConstructorSignature", "namespace_legendary_explorer_core_1_1_gammtek.html#a257e2f7d4427d48f350d0b1740276a3da88199ed5f1baf0dc6ed80a0db9336403", null ],
      [ "InstantiatedNoFixedConstructorSignature", "namespace_legendary_explorer_core_1_1_gammtek.html#a257e2f7d4427d48f350d0b1740276a3da4ea3601c5369a85043a3d88bbe23d4f6", null ]
    ] ],
    [ "ImplicitUseTargetFlags", "namespace_legendary_explorer_core_1_1_gammtek.html#abdb33e0d50e0ed925c43c19bf23e3aec", [
      [ "Default", "namespace_legendary_explorer_core_1_1_gammtek.html#abdb33e0d50e0ed925c43c19bf23e3aeca7a1920d61156abc05a60135aefe8bc67", null ],
      [ "Itself", "namespace_legendary_explorer_core_1_1_gammtek.html#abdb33e0d50e0ed925c43c19bf23e3aecad24a614afd61a4a9097269b8a7225209", null ],
      [ "Members", "namespace_legendary_explorer_core_1_1_gammtek.html#abdb33e0d50e0ed925c43c19bf23e3aecaef53538ae41a651c7f72ab6cb1135d8c", null ],
      [ "WithMembers", "namespace_legendary_explorer_core_1_1_gammtek.html#abdb33e0d50e0ed925c43c19bf23e3aeca5583bb135f4d32715af96327c369e623", null ]
    ] ],
    [ "CollectionAccessType", "namespace_legendary_explorer_core_1_1_gammtek.html#a86220dd30688e36c225063187ae783d3", [
      [ "None", "namespace_legendary_explorer_core_1_1_gammtek.html#a86220dd30688e36c225063187ae783d3a6adf97f83acf6453d4a6a4b1070f3754", null ],
      [ "Read", "namespace_legendary_explorer_core_1_1_gammtek.html#a86220dd30688e36c225063187ae783d3a7a1a5f3e79fdc91edf2f5ead9d66abb4", null ],
      [ "ModifyExistingContent", "namespace_legendary_explorer_core_1_1_gammtek.html#a86220dd30688e36c225063187ae783d3aabf21948b8bdc6b576703a901052dc09", null ],
      [ "UpdatedContent", "namespace_legendary_explorer_core_1_1_gammtek.html#a86220dd30688e36c225063187ae783d3a424cc5446574f01d7f484e158b23d001", null ]
    ] ],
    [ "AssertionConditionType", "namespace_legendary_explorer_core_1_1_gammtek.html#a9433cc61cc685d9cf964d6871ac7e091", [
      [ "IS_TRUE", "namespace_legendary_explorer_core_1_1_gammtek.html#a9433cc61cc685d9cf964d6871ac7e091a23cd5ba5c6eed3d82ba0c6c0526df429", null ],
      [ "IS_FALSE", "namespace_legendary_explorer_core_1_1_gammtek.html#a9433cc61cc685d9cf964d6871ac7e091adeab83d56dee7ab418359a59b4ff2eb0", null ],
      [ "IS_NULL", "namespace_legendary_explorer_core_1_1_gammtek.html#a9433cc61cc685d9cf964d6871ac7e091adbd9c38e0339e6c34bd48cafc59be388", null ],
      [ "IS_NOT_NULL", "namespace_legendary_explorer_core_1_1_gammtek.html#a9433cc61cc685d9cf964d6871ac7e091a05dd132ba23ff57c0ca5ec4100c31fdc", null ]
    ] ]
];