var namespace_legendary_explorer_core_1_1_gammtek_1_1_collections_1_1_specialized =
[
    [ "WeakCollection", "class_legendary_explorer_core_1_1_gammtek_1_1_collections_1_1_specialized_1_1_weak_collection.html", "class_legendary_explorer_core_1_1_gammtek_1_1_collections_1_1_specialized_1_1_weak_collection" ]
];