//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ME3Explorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ME3Explorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding TLK format:.
        /// </summary>
        public static string AboutDecodingTlk {
            get {
                return ResourceManager.GetString("AboutDecodingTlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to TLK, user interface:.
        /// </summary>
        public static string AboutRest {
            get {
                return ResourceManager.GetString("AboutRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Mass Effect 2 TLK Tool.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered. Please report it to the author (Gocek on social.bioware.com)!
        ///.
        /// </summary>
        public static string AlertExceptionGeneric {
            get {
                return ResourceManager.GetString("AlertExceptionGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error description: .
        /// </summary>
        public static string AlertExceptionGenericDescription {
            get {
                return ResourceManager.GetString("AlertExceptionGenericDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading TLK file!
        ///Please make sure you have chosen a file in a TLK format for Mass Effect 2 game..
        /// </summary>
        public static string AlertExceptionTlkFormat {
            get {
                return ResourceManager.GetString("AlertExceptionTlkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected TLK file was not found or is corrupted..
        /// </summary>
        public static string AlertExceptionTlkNotFound {
            get {
                return ResourceManager.GetString("AlertExceptionTlkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected XML file was not found or is corrupted..
        /// </summary>
        public static string AlertExceptionXmlNotFound {
            get {
                return ResourceManager.GetString("AlertExceptionXmlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to read an XML file, which was created in an earlier version of this program! To make it fully compatible with current version, follow instructions in this thread: http://social.bioware.com/project/3492/discussion/2571/ !.
        /// </summary>
        public static string AlertPre103XML {
            get {
                return ResourceManager.GetString("AlertPre103XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished reading TLK file..
        /// </summary>
        public static string AlertTlkLoadingFinished {
            get {
                return ResourceManager.GetString("AlertTlkLoadingFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished creating TLK file..
        /// </summary>
        public static string AlertWritingTlkFinished {
            get {
                return ResourceManager.GetString("AlertWritingTlkFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap animation_explorer_64x64 {
            get {
                object obj = ResourceManager.GetObject("animation_explorer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Effect 2 TLK Tool.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap asset_explorer_64x64 {
            get {
                object obj = ResourceManager.GetObject("asset_explorer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap audio_extract_64x64 {
            get {
                object obj = ResourceManager.GetObject("audio_extract_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap autotoc_64x64 {
            get {
                object obj = ResourceManager.GetObject("autotoc_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Back {
            get {
                object obj = ResourceManager.GetObject("Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap back2 {
            get {
                object obj = ResourceManager.GetObject("back2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backup_64x64 {
            get {
                object obj = ResourceManager.GetObject("backup_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap batch_rename_64x64 {
            get {
                object obj = ResourceManager.GetObject("batch_rename_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BIK_movie_64x64 {
            get {
                object obj = ResourceManager.GetObject("BIK_movie_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap camera_tool_64x64 {
            get {
                object obj = ResourceManager.GetObject("camera_tool_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        public static string ChangeButton {
            get {
                return ResourceManager.GetString("ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test version (displays String ID before every line in-game).
        /// </summary>
        public static string CheckboxDebugTlk {
            get {
                return ResourceManager.GetString("CheckboxDebugTlk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap class_viewer_64x64 {
            get {
                object obj = ResourceManager.GetObject("class_viewer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coaledit {
            get {
                object obj = ResourceManager.GetObject("coaledit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coaledit1 {
            get {
                object obj = ResourceManager.GetObject("coaledit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coalesced_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("coalesced_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap coalesced_operator_64x64 {
            get {
                object obj = ResourceManager.GetObject("coalesced_operator_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap codex_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("codex_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap conditionals_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("conditionals_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path to TLK file:.
        /// </summary>
        public static string CurrentInputTlkFilePath {
            get {
                return ResourceManager.GetString("CurrentInputTlkFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path to XML file:.
        /// </summary>
        public static string CurrentInputXmlFilePath {
            get {
                return ResourceManager.GetString("CurrentInputXmlFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path to output text file:.
        /// </summary>
        public static string CurrentOutputTextFile {
            get {
                return ResourceManager.GetString("CurrentOutputTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current path to output TLK file:.
        /// </summary>
        public static string CurrentOutputTlkFilePath {
            get {
                return ResourceManager.GetString("CurrentOutputTlkFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DDSConverter_64x64 {
            get {
                object obj = ResourceManager.GetObject("DDSConverter_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap decompressor_64x64 {
            get {
                object obj = ResourceManager.GetObject("decompressor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dialogue_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("dialogue_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dlc_basiceditor_64x64 {
            get {
                object obj = ResourceManager.GetObject("dlc_basiceditor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dlc_crackME2_64x64 {
            get {
                object obj = ResourceManager.GetObject("dlc_crackME2_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dlc_editor2_64x64 {
            get {
                object obj = ResourceManager.GetObject("dlc_editor2_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap document_save {
            get {
                object obj = ResourceManager.GetObject("document-save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fxa_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("fxa_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GUIDcache_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("GUIDcache_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap help_browser {
            get {
                object obj = ResourceManager.GetObject("help-browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;Load TLK&apos; tab..
        /// </summary>
        public static string HowTo11 {
            get {
                return ResourceManager.GetString("HowTo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure &apos;Current path to TLK file&apos; points to a TLK file you wish to read from. If it doesn&apos;t - use the &apos;Change&apos; button below it to select your file..
        /// </summary>
        public static string HowTo12 {
            get {
                return ResourceManager.GetString("HowTo12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat step two for &apos;Current path to output text file&apos;. It should point to an XML file you would like to store your text in..
        /// </summary>
        public static string HowTo13 {
            get {
                return ResourceManager.GetString("HowTo13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit &apos;Start!&apos; and wait..
        /// </summary>
        public static string HowTo14 {
            get {
                return ResourceManager.GetString("HowTo14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will see a message saying the work is done and all the data from the TLK file is now in a text file selected before..
        /// </summary>
        public static string HowTo15 {
            get {
                return ResourceManager.GetString("HowTo15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;Create TLK&apos; tab..
        /// </summary>
        public static string HowTo21 {
            get {
                return ResourceManager.GetString("HowTo21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Current path to XML file&apos; should point to the previously created XML file (modified or not). If it doesn&apos;t - use the &apos;Change&apos; button below it to select your file..
        /// </summary>
        public static string HowTo22 {
            get {
                return ResourceManager.GetString("HowTo22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Current path to output TLK file&apos; should point to a new TLK file which will be generated from selected XML file..
        /// </summary>
        public static string HowTo23 {
            get {
                return ResourceManager.GetString("HowTo23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit &apos;Start!&apos; and wait..
        /// </summary>
        public static string HowTo24 {
            get {
                return ResourceManager.GetString("HowTo24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will see a message saying the work is done. Your custom TLK file is ready to be put in an appropriate Mass Effect 2 folder..
        /// </summary>
        public static string HowTo25 {
            get {
                return ResourceManager.GetString("HowTo25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typical usage scenario.
        /// </summary>
        public static string HowToHeader {
            get {
                return ResourceManager.GetString("HowToHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting text from TLK file.
        /// </summary>
        public static string HowToSubheader1 {
            get {
                return ResourceManager.GetString("HowToSubheader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating a new TLK file.
        /// </summary>
        public static string HowToSubheader2 {
            get {
                return ResourceManager.GetString("HowToSubheader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use?.
        /// </summary>
        public static string HowToTitle {
            get {
                return ResourceManager.GetString("HowToTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImageEngine_icon_64x64 {
            get {
                object obj = ResourceManager.GetObject("ImageEngine_icon_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap interp_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("interp_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lang {
            get {
                object obj = ResourceManager.GetObject("lang", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lang_select_64x64 {
            get {
                object obj = ResourceManager.GetObject("lang_select_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lang1 {
            get {
                object obj = ResourceManager.GetObject("lang1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap level_database_64x64 {
            get {
                object obj = ResourceManager.GetObject("level_database_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap level_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("level_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap level_explorer_64x64 {
            get {
                object obj = ResourceManager.GetObject("level_explorer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load TLK file.
        /// </summary>
        public static string LoadTlkTab {
            get {
                return ResourceManager.GetString("LoadTlkTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap material_viewer_64x64 {
            get {
                object obj = ResourceManager.GetObject("material_viewer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap materialviewver {
            get {
                object obj = ResourceManager.GetObject("materialviewver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap materialviewver1 {
            get {
                object obj = ResourceManager.GetObject("materialviewver1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me1exp_64x64 {
            get {
                object obj = ResourceManager.GetObject("me1exp_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me1exp_icon {
            get {
                object obj = ResourceManager.GetObject("me1exp_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me2exp_64x64 {
            get {
                object obj = ResourceManager.GetObject("me2exp_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me2exp_icon {
            get {
                object obj = ResourceManager.GetObject("me2exp_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me3creator_64x64 {
            get {
                object obj = ResourceManager.GetObject("me3creator_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me3exp_64x64 {
            get {
                object obj = ResourceManager.GetObject("me3exp_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me3exp_favicon {
            get {
                object obj = ResourceManager.GetObject("me3exp_favicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me3exp_favicon_64x64 {
            get {
                object obj = ResourceManager.GetObject("me3exp_favicon_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me3exp_newbanner {
            get {
                object obj = ResourceManager.GetObject("me3exp_newbanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me3exp_smallbanner_v1 {
            get {
                object obj = ResourceManager.GetObject("me3exp_smallbanner_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap me3exp_smallbanner_v2 {
            get {
                object obj = ResourceManager.GetObject("me3exp_smallbanner_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meshexplorer {
            get {
                object obj = ResourceManager.GetObject("meshexplorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meshexplorer1 {
            get {
                object obj = ResourceManager.GetObject("meshexplorer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meshplorer_64x64 {
            get {
                object obj = ResourceManager.GetObject("meshplorer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meshplorer2_64x64 {
            get {
                object obj = ResourceManager.GetObject("meshplorer2_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap modmaker_64x64 {
            get {
                object obj = ResourceManager.GetObject("modmaker_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap package_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("package_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PAR_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("PAR_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Patcher {
            get {
                object obj = ResourceManager.GetObject("Patcher", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Patcher1 {
            get {
                object obj = ResourceManager.GetObject("Patcher1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pcc_repacker_64x64 {
            get {
                object obj = ResourceManager.GetObject("pcc_repacker_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pcceditor2_64x64 {
            get {
                object obj = ResourceManager.GetObject("pcceditor2_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap placeholder_64x64 {
            get {
                object obj = ResourceManager.GetObject("placeholder_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plot_DB_64x64 {
            get {
                object obj = ResourceManager.GetObject("plot_DB_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap property_database_64x64 {
            get {
                object obj = ResourceManager.GetObject("property_database_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap property_dumper_64x64 {
            get {
                object obj = ResourceManager.GetObject("property_dumper_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap property_manager_64x64 {
            get {
                object obj = ResourceManager.GetObject("property_manager_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap propertydumper {
            get {
                object obj = ResourceManager.GetObject("propertydumper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap propertydumper1 {
            get {
                object obj = ResourceManager.GetObject("propertydumper1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap psa_viewer_64x64 {
            get {
                object obj = ResourceManager.GetObject("psa_viewer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PSAViewver {
            get {
                object obj = ResourceManager.GetObject("PSAViewver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PSAViewver1 {
            get {
                object obj = ResourceManager.GetObject("PSAViewver1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap psk_viewer_64x64 {
            get {
                object obj = ResourceManager.GetObject("psk_viewer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PSKViewver {
            get {
                object obj = ResourceManager.GetObject("PSKViewver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PSKViewver1 {
            get {
                object obj = ResourceManager.GetObject("PSKViewver1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap questmap_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("questmap_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_gameeditor_64x64 {
            get {
                object obj = ResourceManager.GetObject("save_gameeditor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_gameoperator_64x64 {
            get {
                object obj = ResourceManager.GetObject("save_gameoperator_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap script_compiler_64x64 {
            get {
                object obj = ResourceManager.GetObject("script_compiler_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap script_database_64x64 {
            get {
                object obj = ResourceManager.GetObject("script_database_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sequence_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("sequence_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SFARTOC_64x64 {
            get {
                object obj = ResourceManager.GetObject("SFARTOC_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] shader {
            get {
                object obj = ResourceManager.GetObject("shader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap soundexplorer {
            get {
                object obj = ResourceManager.GetObject("soundexplorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap soundexplorer1 {
            get {
                object obj = ResourceManager.GetObject("soundexplorer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap soundplorer_64x64 {
            get {
                object obj = ResourceManager.GetObject("soundplorer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap subtitle_scanner_64x64 {
            get {
                object obj = ResourceManager.GetObject("subtitle_scanner_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap texplorer {
            get {
                object obj = ResourceManager.GetObject("texplorer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap texplorer_64x64 {
            get {
                object obj = ResourceManager.GetObject("texplorer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml)|*.xml.
        /// </summary>
        public static string TextFilesFilter {
            get {
                return ResourceManager.GetString("TextFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap texturetool_64x64 {
            get {
                object obj = ResourceManager.GetObject("texturetool_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TLK_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("TLK_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon TLK_editor_icon {
            get {
                object obj = ResourceManager.GetObject("TLK_editor_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TLK Files (*.tlk)|*.tlk.
        /// </summary>
        public static string TlkFilesFilter {
            get {
                return ResourceManager.GetString("TlkFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tocbin {
            get {
                object obj = ResourceManager.GetObject("tocbin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TOCbin_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("TOCbin_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TOCbin_editorAK86_64x64 {
            get {
                object obj = ResourceManager.GetObject("TOCbin_editorAK86_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tocbin1 {
            get {
                object obj = ResourceManager.GetObject("tocbin1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tocbin2 {
            get {
                object obj = ResourceManager.GetObject("tocbin2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TOCbinUpdater_64x64 {
            get {
                object obj = ResourceManager.GetObject("TOCbinUpdater_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TPFTools_64x64 {
            get {
                object obj = ResourceManager.GetObject("TPFTools_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap udk_converter_64x64 {
            get {
                object obj = ResourceManager.GetObject("udk_converter_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap udk_explorer_64x64 {
            get {
                object obj = ResourceManager.GetObject("udk_explorer_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ue_codeeditor_64x64 {
            get {
                object obj = ResourceManager.GetObject("ue_codeeditor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap version_checker_64x64 {
            get {
                object obj = ResourceManager.GetObject("version_checker_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap versioncheck {
            get {
                object obj = ResourceManager.GetObject("versioncheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create TLK file.
        /// </summary>
        public static string WriteTlkTab {
            get {
                return ResourceManager.GetString("WriteTlkTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wwisebank_editor_64x64 {
            get {
                object obj = ResourceManager.GetObject("wwisebank_editor_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files (*.xml)|*.xml.
        /// </summary>
        public static string XmlFilesFilter {
            get {
                return ResourceManager.GetString("XmlFilesFilter", resourceCulture);
            }
        }
    }
}
