//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ME3Explorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TexplorerME3Path {
            get {
                return ((string)(this["TexplorerME3Path"]));
            }
            set {
                this["TexplorerME3Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NumThreads {
            get {
                return ((int)(this["NumThreads"]));
            }
            set {
                this["NumThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TexplorerME3DLCPath {
            get {
                return ((string)(this["TexplorerME3DLCPath"]));
            }
            set {
                this["TexplorerME3DLCPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TexplorerGameVersion {
            get {
                return ((int)(this["TexplorerGameVersion"]));
            }
            set {
                this["TexplorerGameVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TexplorerME1Path {
            get {
                return ((string)(this["TexplorerME1Path"]));
            }
            set {
                this["TexplorerME1Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TexplorerME1DLCPath {
            get {
                return ((string)(this["TexplorerME1DLCPath"]));
            }
            set {
                this["TexplorerME1DLCPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TexplorerME2Path {
            get {
                return ((string)(this["TexplorerME2Path"]));
            }
            set {
                this["TexplorerME2Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TexplorerME2DLCPath {
            get {
                return ((string)(this["TexplorerME2DLCPath"]));
            }
            set {
                this["TexplorerME2DLCPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TPFToolsGameVersion {
            get {
                return ((int)(this["TPFToolsGameVersion"]));
            }
            set {
                this["TPFToolsGameVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SoundplorerReverseIDDisplayEndianness {
            get {
                return ((bool)(this["SoundplorerReverseIDDisplayEndianness"]));
            }
            set {
                this["SoundplorerReverseIDDisplayEndianness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlotVarDBPath {
            get {
                return ((string)(this["PlotVarDBPath"]));
            }
            set {
                this["PlotVarDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableToolDescriptions {
            get {
                return ((bool)(this["DisableToolDescriptions"]));
            }
            set {
                this["DisableToolDescriptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseMetadataFullPaths {
            get {
                return ((bool)(this["UseMetadataFullPaths"]));
            }
            set {
                this["UseMetadataFullPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeshplorerViewRotating {
            get {
                return ((bool)(this["MeshplorerViewRotating"]));
            }
            set {
                this["MeshplorerViewRotating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MeshplorerViewWireframeEnabled {
            get {
                return ((bool)(this["MeshplorerViewWireframeEnabled"]));
            }
            set {
                this["MeshplorerViewWireframeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MeshplorerViewSolidEnabled {
            get {
                return ((bool)(this["MeshplorerViewSolidEnabled"]));
            }
            set {
                this["MeshplorerViewSolidEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeshplorerViewFirstPerson {
            get {
                return ((bool)(this["MeshplorerViewFirstPerson"]));
            }
            set {
                this["MeshplorerViewFirstPerson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoundpanelRepeating {
            get {
                return ((bool)(this["SoundpanelRepeating"]));
            }
            set {
                this["SoundpanelRepeating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BinaryInterpreterWPFAutoScanAlways {
            get {
                return ((bool)(this["BinaryInterpreterWPFAutoScanAlways"]));
            }
            set {
                this["BinaryInterpreterWPFAutoScanAlways"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropertyParsingME3UnknownArrayAsObject {
            get {
                return ((bool)(this["PropertyParsingME3UnknownArrayAsObject"]));
            }
            set {
                this["PropertyParsingME3UnknownArrayAsObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropertyParsingME2UnknownArrayAsObject {
            get {
                return ((bool)(this["PropertyParsingME2UnknownArrayAsObject"]));
            }
            set {
                this["PropertyParsingME2UnknownArrayAsObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropertyParsingME1UnknownArrayAsObject {
            get {
                return ((bool)(this["PropertyParsingME1UnknownArrayAsObject"]));
            }
            set {
                this["PropertyParsingME1UnknownArrayAsObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PathfindingEditorShowNodeSizes {
            get {
                return ((bool)(this["PathfindingEditorShowNodeSizes"]));
            }
            set {
                this["PathfindingEditorShowNodeSizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PackageEditorWPF_TreeViewShowEntryIndex {
            get {
                return ((bool)(this["PackageEditorWPF_TreeViewShowEntryIndex"]));
            }
            set {
                this["PackageEditorWPF_TreeViewShowEntryIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmbeddedTextureViewer_AutoLoad {
            get {
                return ((bool)(this["EmbeddedTextureViewer_AutoLoad"]));
            }
            set {
                this["EmbeddedTextureViewer_AutoLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InterpreterWPF_AdvancedDisplay {
            get {
                return ((bool)(this["InterpreterWPF_AdvancedDisplay"]));
            }
            set {
                this["InterpreterWPF_AdvancedDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TouchComfyMode {
            get {
                return ((bool)(this["TouchComfyMode"]));
            }
            set {
                this["TouchComfyMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InterpreterWPF_Colorize {
            get {
                return ((bool)(this["InterpreterWPF_Colorize"]));
            }
            set {
                this["InterpreterWPF_Colorize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ME1Directory {
            get {
                return ((string)(this["ME1Directory"]));
            }
            set {
                this["ME1Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ME2Directory {
            get {
                return ((string)(this["ME2Directory"]));
            }
            set {
                this["ME2Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ME3Directory {
            get {
                return ((string)(this["ME3Directory"]));
            }
            set {
                this["ME3Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PropertyDBPath {
            get {
                return ((string)(this["PropertyDBPath"]));
            }
            set {
                this["PropertyDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TLKGender_IsMale {
            get {
                return ((bool)(this["TLKGender_IsMale"]));
            }
            set {
                this["TLKGender_IsMale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INT")]
        public string TLKLanguage {
            get {
                return ((string)(this["TLKLanguage"]));
            }
            set {
                this["TLKLanguage"] = value;
            }
        }
    }
}
