//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ME3Explorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SoundplorerReverseIDDisplayEndianness {
            get {
                return ((bool)(this["SoundplorerReverseIDDisplayEndianness"]));
            }
            set {
                this["SoundplorerReverseIDDisplayEndianness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlotVarDBPath {
            get {
                return ((string)(this["PlotVarDBPath"]));
            }
            set {
                this["PlotVarDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableToolDescriptions {
            get {
                return ((bool)(this["DisableToolDescriptions"]));
            }
            set {
                this["DisableToolDescriptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseMetadataFullPaths {
            get {
                return ((bool)(this["UseMetadataFullPaths"]));
            }
            set {
                this["UseMetadataFullPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeshplorerViewRotating {
            get {
                return ((bool)(this["MeshplorerViewRotating"]));
            }
            set {
                this["MeshplorerViewRotating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MeshplorerViewWireframeEnabled {
            get {
                return ((bool)(this["MeshplorerViewWireframeEnabled"]));
            }
            set {
                this["MeshplorerViewWireframeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MeshplorerViewSolidEnabled {
            get {
                return ((bool)(this["MeshplorerViewSolidEnabled"]));
            }
            set {
                this["MeshplorerViewSolidEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MeshplorerViewFirstPerson {
            get {
                return ((bool)(this["MeshplorerViewFirstPerson"]));
            }
            set {
                this["MeshplorerViewFirstPerson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoundpanelRepeating {
            get {
                return ((bool)(this["SoundpanelRepeating"]));
            }
            set {
                this["SoundpanelRepeating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BinaryInterpreterWPFAutoScanAlways {
            get {
                return ((bool)(this["BinaryInterpreterWPFAutoScanAlways"]));
            }
            set {
                this["BinaryInterpreterWPFAutoScanAlways"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropertyParsingME3UnknownArrayAsObject {
            get {
                return ((bool)(this["PropertyParsingME3UnknownArrayAsObject"]));
            }
            set {
                this["PropertyParsingME3UnknownArrayAsObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropertyParsingME2UnknownArrayAsObject {
            get {
                return ((bool)(this["PropertyParsingME2UnknownArrayAsObject"]));
            }
            set {
                this["PropertyParsingME2UnknownArrayAsObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropertyParsingME1UnknownArrayAsObject {
            get {
                return ((bool)(this["PropertyParsingME1UnknownArrayAsObject"]));
            }
            set {
                this["PropertyParsingME1UnknownArrayAsObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PathfindingEditorShowNodeSizes {
            get {
                return ((bool)(this["PathfindingEditorShowNodeSizes"]));
            }
            set {
                this["PathfindingEditorShowNodeSizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EmbeddedTextureViewer_AutoLoad {
            get {
                return ((bool)(this["EmbeddedTextureViewer_AutoLoad"]));
            }
            set {
                this["EmbeddedTextureViewer_AutoLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InterpreterWPF_AdvancedDisplay {
            get {
                return ((bool)(this["InterpreterWPF_AdvancedDisplay"]));
            }
            set {
                this["InterpreterWPF_AdvancedDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TouchComfyMode {
            get {
                return ((bool)(this["TouchComfyMode"]));
            }
            set {
                this["TouchComfyMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InterpreterWPF_Colorize {
            get {
                return ((bool)(this["InterpreterWPF_Colorize"]));
            }
            set {
                this["InterpreterWPF_Colorize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ME1Directory {
            get {
                return ((string)(this["ME1Directory"]));
            }
            set {
                this["ME1Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ME2Directory {
            get {
                return ((string)(this["ME2Directory"]));
            }
            set {
                this["ME2Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ME3Directory {
            get {
                return ((string)(this["ME3Directory"]));
            }
            set {
                this["ME3Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AssetDBPath {
            get {
                return ((string)(this["AssetDBPath"]));
            }
            set {
                this["AssetDBPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TLKGender_IsMale {
            get {
                return ((bool)(this["TLKGender_IsMale"]));
            }
            set {
                this["TLKGender_IsMale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INT")]
        public string TLKLanguage {
            get {
                return ((string)(this["TLKLanguage"]));
            }
            set {
                this["TLKLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InterpreterWPF_LimitArrayPropertySize {
            get {
                return ((bool)(this["InterpreterWPF_LimitArrayPropertySize"]));
            }
            set {
                this["InterpreterWPF_LimitArrayPropertySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PackageEditorWPF_ShowImpExpPrefix {
            get {
                return ((bool)(this["PackageEditorWPF_ShowImpExpPrefix"]));
            }
            set {
                this["PackageEditorWPF_ShowImpExpPrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PackageEditorWPF_ShowExportIcons {
            get {
                return ((bool)(this["PackageEditorWPF_ShowExportIcons"]));
            }
            set {
                this["PackageEditorWPF_ShowExportIcons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SequenceEditor_ShowParsedInfo {
            get {
                return ((bool)(this["SequenceEditor_ShowParsedInfo"]));
            }
            set {
                this["SequenceEditor_ShowParsedInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public ushort SequenceEditor_MaxVarStringLength {
            get {
                return ((ushort)(this["SequenceEditor_MaxVarStringLength"]));
            }
            set {
                this["SequenceEditor_MaxVarStringLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#999999")]
        public string MeshplorerBackgroundColor {
            get {
                return ((string)(this["MeshplorerBackgroundColor"]));
            }
            set {
                this["MeshplorerBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ME3")]
        public string AssetDBGame {
            get {
                return ((string)(this["AssetDBGame"]));
            }
            set {
                this["AssetDBGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PackageEditor_HideInterpreterHexBox {
            get {
                return ((bool)(this["PackageEditor_HideInterpreterHexBox"]));
            }
            set {
                this["PackageEditor_HideInterpreterHexBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UDKCustomPath {
            get {
                return ((string)(this["UDKCustomPath"]));
            }
            set {
                this["UDKCustomPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InterpreterWPF_ShowLinearColorWheel {
            get {
                return ((bool)(this["InterpreterWPF_ShowLinearColorWheel"]));
            }
            set {
                this["InterpreterWPF_ShowLinearColorWheel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PackageEditorWPF_ShowSubText {
            get {
                return ((bool)(this["PackageEditorWPF_ShowSubText"]));
            }
            set {
                this["PackageEditorWPF_ShowSubText"] = value;
            }
        }
    }
}
