//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassEffect2.SaveFormats.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlotTableWrapper {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotTableWrapper() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MassEffect2.SaveFormats.Localization.PlotTableWrapper", typeof(PlotTableWrapper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had Cosmetic Surgery in ME2.
        /// </summary>
        public static string CosmeticSurgeryMe2_DisplayName {
            get {
                return ResourceManager.GetString("CosmeticSurgeryMe2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had Cosmetic Surgery in ME3.
        /// </summary>
        public static string CosmeticSurgeryMe3_DisplayName {
            get {
                return ResourceManager.GetString("CosmeticSurgeryMe3_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Medi-gel.
        /// </summary>
        public static string ExtraMedigel_DisplayName {
            get {
                return ResourceManager.GetString("ExtraMedigel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is ME1 Import.
        /// </summary>
        public static string IsMe1Import_DisplayName {
            get {
                return ResourceManager.GetString("IsMe1Import_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is ME2 Import.
        /// </summary>
        public static string IsMe2Import_DisplayName {
            get {
                return ResourceManager.GetString("IsMe2Import_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game+ Count.
        /// </summary>
        public static string NewGamePlusCount_DisplayName {
            get {
                return ResourceManager.GetString("NewGamePlusCount_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragon Points.
        /// </summary>
        public static string ParagonPoints_DisplayName {
            get {
                return ResourceManager.GetString("ParagonPoints_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persuade Multiplier.
        /// </summary>
        public static string PersuadeMultiplier_DisplayName {
            get {
                return ResourceManager.GetString("PersuadeMultiplier_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renegade Points.
        /// </summary>
        public static string RenegadePoints_DisplayName {
            get {
                return ResourceManager.GetString("RenegadePoints_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        public static string Reputation_DisplayName {
            get {
                return ResourceManager.GetString("Reputation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation Points.
        /// </summary>
        public static string ReputationPoints_DisplayName {
            get {
                return ResourceManager.GetString("ReputationPoints_DisplayName", resourceCulture);
            }
        }
    }
}
