//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gammtek.Conduit.MassEffect3.SaveFornats.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Appearance {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Appearance() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gammtek.Conduit.MassEffect3.SaveFornats.Localization.Appearance", typeof(Appearance).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm ID.
        /// </summary>
        public static string ArmId_DisplayName {
            get {
                return ResourceManager.GetString("ArmId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Body.
        /// </summary>
        public static string Body_Category {
            get {
                return ResourceManager.GetString("Body_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual ID.
        /// </summary>
        public static string CasualId_DisplayName {
            get {
                return ResourceManager.GetString("CasualId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Appearance.
        /// </summary>
        public static string CombatAppearance_DisplayName {
            get {
                return ResourceManager.GetString("CombatAppearance_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emissive ID.
        /// </summary>
        public static string EmissiveId_DisplayName {
            get {
                return ResourceManager.GetString("EmissiveId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Body ID.
        /// </summary>
        public static string FullBodyId_DisplayName {
            get {
                return ResourceManager.GetString("FullBodyId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Head Morph.
        /// </summary>
        public static string HasMorphHead_DisplayName {
            get {
                return ResourceManager.GetString("HasMorphHead_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Head.
        /// </summary>
        public static string Head_Category {
            get {
                return ResourceManager.GetString("Head_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helmet ID.
        /// </summary>
        public static string HelmetId_DisplayName {
            get {
                return ResourceManager.GetString("HelmetId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leg ID.
        /// </summary>
        public static string LegId_DisplayName {
            get {
                return ResourceManager.GetString("LegId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Morph.
        /// </summary>
        public static string MorphHead_DisplayName {
            get {
                return ResourceManager.GetString("MorphHead_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Color ID.
        /// </summary>
        public static string PatternColorId_DisplayName {
            get {
                return ResourceManager.GetString("PatternColorId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern ID.
        /// </summary>
        public static string PatternId_DisplayName {
            get {
                return ResourceManager.GetString("PatternId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoulder ID.
        /// </summary>
        public static string ShoulderId_DisplayName {
            get {
                return ResourceManager.GetString("ShoulderId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specular ID.
        /// </summary>
        public static string SpecId_DisplayName {
            get {
                return ResourceManager.GetString("SpecId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tint #1 ID.
        /// </summary>
        public static string Tint1Id_DisplayName {
            get {
                return ResourceManager.GetString("Tint1Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tint #2 ID.
        /// </summary>
        public static string Tint2Id_DisplayName {
            get {
                return ResourceManager.GetString("Tint2Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tint #3 ID.
        /// </summary>
        public static string Tint3Id_DisplayName {
            get {
                return ResourceManager.GetString("Tint3Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torso ID.
        /// </summary>
        public static string TorsoId_DisplayName {
            get {
                return ResourceManager.GetString("TorsoId_DisplayName", resourceCulture);
            }
        }
    }
}
