//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gammtek.Conduit.MassEffect3.SaveFornats.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MorphHead {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MorphHead() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gammtek.Conduit.MassEffect3.SaveFornats.Localization.MorphHead", typeof(MorphHead).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessory Meshes.
        /// </summary>
        public static string AccessoryMeshes_DisplayName {
            get {
                return ResourceManager.GetString("AccessoryMeshes_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair Mesh.
        /// </summary>
        public static string HairMesh_DisplayName {
            get {
                return ResourceManager.GetString("HairMesh_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOD #0 Vertices.
        /// </summary>
        public static string Lod0Vertices_DisplayName {
            get {
                return ResourceManager.GetString("Lod0Vertices_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOD #1 Vertices.
        /// </summary>
        public static string Lod1Vertices_DisplayName {
            get {
                return ResourceManager.GetString("Lod1Vertices_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOD #2 Vertices.
        /// </summary>
        public static string Lod2Vertices_DisplayName {
            get {
                return ResourceManager.GetString("Lod2Vertices_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOD #3 Vertices.
        /// </summary>
        public static string Lod3Vertices_DisplayName {
            get {
                return ResourceManager.GetString("Lod3Vertices_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        public static string MorphFeature_Feature_DisplayName {
            get {
                return ResourceManager.GetString("MorphFeature_Feature_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string MorphFeature_Offset_DisplayName {
            get {
                return ResourceManager.GetString("MorphFeature_Offset_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Morphs.
        /// </summary>
        public static string MorphFeatures_DisplayName {
            get {
                return ResourceManager.GetString("MorphFeatures_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string OffsetBone_Name_DisplayName {
            get {
                return ResourceManager.GetString("OffsetBone_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        public static string OffsetBone_Offset_DisplayName {
            get {
                return ResourceManager.GetString("OffsetBone_Offset_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Bones.
        /// </summary>
        public static string OffsetBones_DisplayName {
            get {
                return ResourceManager.GetString("OffsetBones_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ScalarParameter_Name_DisplayName {
            get {
                return ResourceManager.GetString("ScalarParameter_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ScalarParameter_Value_DisplayName {
            get {
                return ResourceManager.GetString("ScalarParameter_Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar Parameters.
        /// </summary>
        public static string ScalarParameters_DisplayName {
            get {
                return ResourceManager.GetString("ScalarParameters_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TextureParameter_Name_DisplayName {
            get {
                return ResourceManager.GetString("TextureParameter_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string TextureParameter_Value_DisplayName {
            get {
                return ResourceManager.GetString("TextureParameter_Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Parameters.
        /// </summary>
        public static string TextureParameters_DisplayName {
            get {
                return ResourceManager.GetString("TextureParameters_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string VectorParameter_Name_DisplayName {
            get {
                return ResourceManager.GetString("VectorParameter_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string VectorParameter_Value_DisplayName {
            get {
                return ResourceManager.GetString("VectorParameter_Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector Parameters.
        /// </summary>
        public static string VectorParameters_DisplayName {
            get {
                return ResourceManager.GetString("VectorParameters_DisplayName", resourceCulture);
            }
        }
    }
}
