//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gammtek.Conduit.MassEffect3.SaveFornats.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Player {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Player() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gammtek.Conduit.MassEffect3.SaveFornats.Localization.Player", typeof(Player).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance_DisplayName {
            get {
                return ResourceManager.GetString("Appearance_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Friendly Name.
        /// </summary>
        public static string ClassFriendlyName_DisplayName {
            get {
                return ResourceManager.GetString("ClassFriendlyName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Name.
        /// </summary>
        public static string ClassName_DisplayName {
            get {
                return ResourceManager.GetString("ClassName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits_DisplayName {
            get {
                return ResourceManager.GetString("Credits_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Fuel.
        /// </summary>
        public static string CurrentFuel_DisplayName {
            get {
                return ResourceManager.GetString("CurrentFuel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Health.
        /// </summary>
        public static string CurrentHealth_DisplayName {
            get {
                return ResourceManager.GetString("CurrentHealth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current XP.
        /// </summary>
        public static string CurrentXP_DisplayName {
            get {
                return ResourceManager.GetString("CurrentXP_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eezo.
        /// </summary>
        public static string Eezo_DisplayName {
            get {
                return ResourceManager.GetString("Eezo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Code.
        /// </summary>
        public static string FaceCode_DisplayName {
            get {
                return ResourceManager.GetString("FaceCode_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName_DisplayName {
            get {
                return ResourceManager.GetString("FirstName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAW Assets.
        /// </summary>
        public static string GAWAssets_DisplayName {
            get {
                return ResourceManager.GetString("GAWAssets_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grenades.
        /// </summary>
        public static string Grenades_DisplayName {
            get {
                return ResourceManager.GetString("Grenades_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        public static string Guid_DisplayName {
            get {
                return ResourceManager.GetString("Guid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string HotKeys_DisplayName {
            get {
                return ResourceManager.GetString("HotKeys_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iridium.
        /// </summary>
        public static string Iridium_DisplayName {
            get {
                return ResourceManager.GetString("Iridium_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Combat Pawn.
        /// </summary>
        public static string IsCombatPawn_DisplayName {
            get {
                return ResourceManager.GetString("IsCombatPawn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Female.
        /// </summary>
        public static string IsFemale_DisplayName {
            get {
                return ResourceManager.GetString("IsFemale_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Injured Pawn.
        /// </summary>
        public static string IsInjuredPawn_DisplayName {
            get {
                return ResourceManager.GetString("IsInjuredPawn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName_DisplayName {
            get {
                return ResourceManager.GetString("LastName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level_DisplayName {
            get {
                return ResourceManager.GetString("Level_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Loadout Groups.
        /// </summary>
        public static string LoadoutWeaponGroups_DisplayName {
            get {
                return ResourceManager.GetString("LoadoutWeaponGroups_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Loadout.
        /// </summary>
        public static string LoadoutWeapons_DisplayName {
            get {
                return ResourceManager.GetString("LoadoutWeapons_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped Power #1.
        /// </summary>
        public static string MappedPower1_DisplayName {
            get {
                return ResourceManager.GetString("MappedPower1_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped Power #2.
        /// </summary>
        public static string MappedPower2_DisplayName {
            get {
                return ResourceManager.GetString("MappedPower2_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped Power #3.
        /// </summary>
        public static string MappedPower3_DisplayName {
            get {
                return ResourceManager.GetString("MappedPower3_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medi-gel.
        /// </summary>
        public static string Medigel_DisplayName {
            get {
                return ResourceManager.GetString("Medigel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notoriety.
        /// </summary>
        public static string Notoriety_DisplayName {
            get {
                return ResourceManager.GetString("Notoriety_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin_DisplayName {
            get {
                return ResourceManager.GetString("Origin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palladium.
        /// </summary>
        public static string Palladium_DisplayName {
            get {
                return ResourceManager.GetString("Palladium_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinum.
        /// </summary>
        public static string Platinum_DisplayName {
            get {
                return ResourceManager.GetString("Platinum_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powers.
        /// </summary>
        public static string Powers_DisplayName {
            get {
                return ResourceManager.GetString("Powers_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Weapon.
        /// </summary>
        public static string PrimaryWeapon_DisplayName {
            get {
                return ResourceManager.GetString("PrimaryWeapon_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probes.
        /// </summary>
        public static string Probes_DisplayName {
            get {
                return ResourceManager.GetString("Probes_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Weapon.
        /// </summary>
        public static string SecondaryWeapon_DisplayName {
            get {
                return ResourceManager.GetString("SecondaryWeapon_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talent Points.
        /// </summary>
        public static string TalentPoints_DisplayName {
            get {
                return ResourceManager.GetString("TalentPoints_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Casual Appearance.
        /// </summary>
        public static string UseCasualAppearance_DisplayName {
            get {
                return ResourceManager.GetString("UseCasualAppearance_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Mods.
        /// </summary>
        public static string WeaponMods_DisplayName {
            get {
                return ResourceManager.GetString("WeaponMods_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        public static string Weapons_DisplayName {
            get {
                return ResourceManager.GetString("Weapons_DisplayName", resourceCulture);
            }
        }
    }
}
