//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gammtek.Conduit.MassEffect3.SaveFornats.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlotTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlotTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gammtek.Conduit.MassEffect3.SaveFornats.Localization.PlotTable", typeof(PlotTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bool Variables.
        /// </summary>
        public static string BoolVariables_DisplayName {
            get {
                return ResourceManager.GetString("BoolVariables_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bool Variables.
        /// </summary>
        public static string BoolVariablesWrapper_DisplayName {
            get {
                return ResourceManager.GetString("BoolVariablesWrapper_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codex Entries.
        /// </summary>
        public static string CodexEntries_DisplayName {
            get {
                return ResourceManager.GetString("CodexEntries_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codex IDs.
        /// </summary>
        public static string CodexIDs_DisplayName {
            get {
                return ResourceManager.GetString("CodexIDs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string FloatVariablePair_Index_DisplayName {
            get {
                return ResourceManager.GetString("FloatVariablePair_Index_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string FloatVariablePair_Value_DisplayName {
            get {
                return ResourceManager.GetString("FloatVariablePair_Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Float Variables.
        /// </summary>
        public static string FloatVariables_DisplayName {
            get {
                return ResourceManager.GetString("FloatVariables_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known Variables.
        /// </summary>
        public static string Helpers_DisplayName {
            get {
                return ResourceManager.GetString("Helpers_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string IntVariablePair_Index_DisplayName {
            get {
                return ResourceManager.GetString("IntVariablePair_Index_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string IntVariablePair_Value_DisplayName {
            get {
                return ResourceManager.GetString("IntVariablePair_Value_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Int Variables.
        /// </summary>
        public static string IntVariables_DisplayName {
            get {
                return ResourceManager.GetString("IntVariables_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string PlotCodex_Pages_DisplayName {
            get {
                return ResourceManager.GetString("PlotCodex_Pages_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is New.
        /// </summary>
        public static string PlotCodex_PlotCodexPage_IsNew_DisplayName {
            get {
                return ResourceManager.GetString("PlotCodex_PlotCodexPage_IsNew_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string PlotCodex_PlotCodexPage_Page_DisplayName {
            get {
                return ResourceManager.GetString("PlotCodex_PlotCodexPage_Page_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Goal.
        /// </summary>
        public static string PlotQuest_ActiveGoal_DisplayName {
            get {
                return ResourceManager.GetString("PlotQuest_ActiveGoal_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string PlotQuest_History_DisplayName {
            get {
                return ResourceManager.GetString("PlotQuest_History_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Counter.
        /// </summary>
        public static string PlotQuest_QuestCounter_DisplayName {
            get {
                return ResourceManager.GetString("PlotQuest_QuestCounter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Updated.
        /// </summary>
        public static string PlotQuest_QuestUpdated_DisplayName {
            get {
                return ResourceManager.GetString("PlotQuest_QuestUpdated_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest IDs.
        /// </summary>
        public static string QuestIDs_DisplayName {
            get {
                return ResourceManager.GetString("QuestIDs_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Progress.
        /// </summary>
        public static string QuestProgress_DisplayName {
            get {
                return ResourceManager.GetString("QuestProgress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest Progress Counter.
        /// </summary>
        public static string QuestProgressCounter_DisplayName {
            get {
                return ResourceManager.GetString("QuestProgressCounter_DisplayName", resourceCulture);
            }
        }
    }
}
