<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
	    <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>

        <Platforms>x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
        <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
        <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
        <PackageReference Include="coverlet.collector" Version="6.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NSubstitute" Version="5.3.0" />
    </ItemGroup>
    
    <ItemGroup>
        <Folder Include="TestData\*" />
    </ItemGroup>

    <ItemGroup>
        <None Include="TestData\**" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LegendaryExplorerCore\LegendaryExplorerCore.csproj" />
      <ProjectReference Include="..\LegendaryExplorer\LegendaryExplorer.csproj" />
    </ItemGroup>

</Project>
